### ISSUE TITLE
How can I disable output report in Pretty Diff command line version?

### ISSUE THREAD

**Issue by setzer17** [prettydiff/prettydiff#151]
Hello,
I want to compare 2 files, but I don't need a report. I just want to know if there are differences or not. I don't even care about the count of differences.
For example:
**prettydiff source:"file1" diff:"file2"**
OUTPUT:
*No differences.*

How is that possible?
Thanks.

**Comment by prettydiff** [comment]
This feature does not exist, but can be a new option.

**Comment by prettydiff** [comment]
I created a new Node only option: `summaryonly`.  Give that guy a value of true to get what you want.

Steps to test this out:

1. `npm install prettydiff`
2. `cd node_modules/prettydiff`
3. Get the updated file: http://prettydiff.com/ignore/testlocation/api/node-local.js and save it over the local file at api/node-local.js
4. `node api/node-local.js source"../someDirectory" diff: "../someOtherDirectory" readmethod:"subdirectory" summaryonly:"true"

Please let me know your feedback.

**Comment by setzer17** [comment]
Hello,
Thanks for the update. But I have no idea what's happening now...

I am trying to compare 2 HTML files. These 2 options give me the same result. Either of them outputs the same result:
**node api/node-local.js source:"../dir1" diff:"../dir2" readmethod:"subdirectory" summaryonly:"true"**
and
**node api/node-local.js source:"../dir1" diff:"../dir2" readmethod:"subdirectory"**

If the 2 files are completely identical, I get:
*Pretty Diff found 0 differences in 1 file out of 1 file. 0 files added. 0 files deleted. Executed in 0.069 seconds.*

If I just switch the order of 2 element attributes for example in one file, (which shouldn't be a difference), after I run one of the commands again, I get the entire source file output to the console + the following lines:
*/home/user/node_modules/prettydiff/api/node-local.js:1553
                pdlen  = output[0].length;
                                  ^
TypeError: Cannot read property 'length' of undefined
    at cliWrite (/home/abdou/node_modules/prettydiff/api/node-local.js:1553:35)
    at fileComplete (/home/abdou/node_modules/prettydiff/api/node-local.js:1647:21)
    at /home/abdou/node_modules/prettydiff/api/node-local.js:1680:17
    at fs.js:268:14
    at Object.oncomplete (fs.js:107:15)*

I honestly have no idea what may be wrong :p
Also, if readmethod is file and summaryonly is true, there is no need for the output argument. But currently:
**node api/node-local.js source:"file1.html" diff:"file2.html" readmethod:"file" summaryonly:"true"**
OUTPUT:
*Error: 'readmethod' is value 'file' and argument 'output' is empty*

**Comment by prettydiff** [comment]
Did you get the updated code from http://prettydiff.com/ignore/testlocation/api/node-local.js ? The first error that you described is a valid production error, but it is resolved in the updated code.  The second problem you mentioned is now resolved as well.

**Comment by setzer17** [comment]
I downloaded the updated code from http://prettydiff.com/ignore/testlocation/api/node-local.js, and I am still facing the same problems. Maybe the file is not getting updated?

**Comment by prettydiff** [comment]
I am so sorry.  I forgot that I was developing in an alternate location on my local to test this enhancements against large directory trees.  I just verify, from actually reading the code, that it is updated at the mentioned location: http://prettydiff.com/ignore/testlocation/api/node-local.js

**Comment by setzer17** [comment]
Thanks a lot for the update (Y)

Here are some tests that I did:
Files **test1.html** and **test2.html** both identical and contain:
```html
<!DOCTYPE html>
<html>
<head>
	<title>Test</title>
</head>
<body>
	<a target="_blank" href="http://prettydiff.com">Pretty Diff</a>
</body>
</html>
```
I ran the following command. It outputs nothing:
**node node-local.js source:"test1.html" diff:"test2.html" readmethod:"file" summaryonly:"true"**

If I add some extra white space to **test1.html**, and run the same command again, I get:
```
Files changed:
test1.html

Pretty Diff found 0 differences. Executed in 0.094 seconds.
```

Then I changed **test1.html** by adding a trailing slash / to the href attribute:
```html
<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
</head>
<body>
    <a target="_blank" href="http://prettydiff.com/">Pretty Diff</a>
</body>
</html>
```

I ran the same command again, and I got this output:
```
Files changed:
test1.html

Pretty Diff found 2 differences. Executed in 0.098 seconds.
```

I am not sure if the output is correct. Cause adding a trailing / after the domain name should not make a difference. Also, the same thing goes for other attributes that may contain trailing spaces or semicolons like the style attribute. I think that can be considered as white space, and it should be trimmed.
Again, I don't know if these types of differences should be ignored or not. Please correct me if I'm wrong.

**Comment by prettydiff** [comment]
Thanks for finding these.  I plan to push this change to production tonight.  I hope the output (when you do get output) is exactly the kind of thing you are hoping for.

The first finding is a defect.  Before running two files through Pretty Diff I do a quick string compare on the contents as well as the file paths and if identical I don't bother.  You should still get that brief summary that the job concluded though.

The second issue is probably a simple off by one counting problem in my node library.  I will check on this further tonight.

**Comment by prettydiff** [comment]
I have not fixed the count issue yet, but will work on that shortly.  Otherwise the updated code is released.
