### ISSUE TITLE
CFML support

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#158]
Add support for ColdFusion markup language.

* create a new type in the parser `pragma`, which will include SGML tags, XML pragmas, and: cfset, cfhttp
* cfelse needs to be added as a template "else" type in my parser.
* self-closing tags:  cfinput, cfgridcolumn, cfset, cfinclude, cfimport

I am having trouble finding a comprehensive list of CF11 tags and then having more diffecultly still determining which of those tags does not require an end tag.  If I know which tags are self-closing tags I can ensure they are treated as self-closing tags even if they end with `>` instead of `/>`.

The parser will not be intelligent enough to know if a custom tag should be self-closing by tag name alone.  These tags will be treated as self-closing tags if they terminate with `/>` otherwise they will be start tags that increase indentation.

**Comment by finalcut** [comment]
Here is a full list of Coldfusion 11 Tags: http://cfdocs.org/tags

I'll try to go through them all and let you know which ones AREN'T self closing (I imagine that list is a lot shorter than the alternate).

**Comment by prettydiff** [comment]
Awesome.  With that I can move this issue forward.

**Comment by finalcut** [comment]
I created a google spreadsheet with them broken down but some tags are a little tricky and don't clean fit in either the self closing or non-self closing department.  They can be self closing OR they can have a matching end tag later after some subordinate tags or content.

https://docs.google.com/spreadsheets/d/1Sr-4kYgRI6WV6PJShtvjvyP4VhVM8ONvHk95MyRjiGw/edit?usp=sharing

I can create a third column on the sheet if you want those ones separate.  Currently they are in the SELF-CLOSING column.

**Comment by finalcut** [comment]
I have updated the spreadsheet using lucee which is a competitive coldfusion project.  It has support for a couple extra functions which I was able to use to programatically get the definition of the various tags and thus extract their tag body rules:

There are three columns: end tag required, end tag optional, and end tag prohibitied.
https://docs.google.com/spreadsheets/d/1Sr-4kYgRI6WV6PJShtvjvyP4VhVM8ONvHk95MyRjiGw/edit#gid=925727260

**Comment by prettydiff** [comment]
I can see that `abort ` is in the end tag prohibited column.  Would it throw an error if I added a trailing slash to the tag?  Example:

    <cfabort showerror="CFABORT has been called for no good reason"/>

I prefer to add trailing slashes to all tags that don't require an end tag as it helps preference best practices and code that is easier to read and troubleshoot.

I will treat the `else` and `elseif` tags in a special way.  I already have a type defined for `else` type tags because they have to reduce preceding indentation by 1 step and push indentation back out 1 step immediately after.

**Comment by prettydiff** [comment]
@finalcut I believe your tag table is valuable for anybody who wishes to write parsers for this language, so I am providing it here as a markdown table, which should allow simple redistribution in a plain text form.  This is the text (code) form of the table for easy copy/pasting.

```markupdown
endtag required | endtag optional     | endtag prohibited
--------------- | ------------------- | -----------------
case            | _                   | abort
catch           | ajaximport          | applet
component       | ajaxproxy           | application
defaultcase     | cache               | argument
execute         | chart               | associate
finally	        | chartseries         | authenticate
form            | content             | break
function        | div                 | chartdata
graph           | document            | col
if              | documentitem        | collection
interface       | documentsection     | continue
login           | dump                | cookie
loop            | file                | dbinfo
mail            | htmlbody            | directory
mailpart        | htmlhead            | else
output          | http                | elseif
query           | invoke              | error
savecontent     | layout              | exit
script          | layoutarea          | feed
select          | map                 | flush
silent          | mapitem             | forward
static          | module              | ftp
stopwatch       | pageencoding        | graphdata
switch          | pdf                 | header
table           | processingdirective | httpparam
timer           | setting             | image
transaction     | storedproc          | imap
try             | thread              | import
while           | trace               | include
xml             | videoplayer         | index
                | window              | input
                | zip                 | insert
                |                     | invokeargument
                |                     | ldap
                |                     | location
                |                     | log
                |                     | loginuser
                |                     | logout
                |                     | mailparam
                |                     | object
                |                     | objectcache
                |                     | param
                |                     | pdfparam
                |                     | pop
                |                     | procparam
                |                     | procresult
                |                     | property
                |                     | queryparam
                |                     | registry
                |                     | rethrow
                |                     | retry
                |                     | return
                |                     | schedule
                |                     | search
                |                     | servlet
                |                     | servletparam
                |                     | set
                |                     | sleep
                |                     | slider
                |                     | throw
                |                     | update
                |                     | video
                |                     | wddx
                |                     | x_
                |                     | zipparam
```

**Comment by finalcut** [comment]
cfabort does not fail if you write: `<cfabort />`

and, stupidly it also won't fail if you write `<cfabort></cfabort>`

but something like `<cfelse>`  will fail if you do `<cfelse />`

This just further reminds me of how stupidly CFML is designed.

**Comment by finalcut** [comment]
Let me add that there is a newish bug in CF that deals specifically with trailing slashes on tags that don't really call for them; specifically `<cfpop>` which suddenly stopped populating the `name` attribute with the query if you used the trailing slash.

http://blog.adamcameron.me/2015/11/caution-latest-coldfusion-11-patch.html

makes me think that best practice is probably to NOT use a trailing slash when they are unneeded (which would be a hard habit for me to break at this point).

on the bright side, Adobe did release a hotfix that patches the aforementioned problem already:
http://blog.adamcameron.me/2015/11/and-adobe-hotfixes-it.html

**Comment by finalcut** [comment]
Here is the Coldfusion code I used to generate the tag table.  This way the table can easily be regenerated for future versions of CF. **NOTE** the code has to be run on a lucee server not an adobe one as adobe doesn't actually provide this kind of tag level information:

```cfm
<cfset tags = GetTagList() />


<cfset bodies = structNew() />
<cfset namespace  = "cf" />
<cfset tags = tags[namespace] />
<cfset maxLength = 0 >


<cfloop list="#StructKeyList(tags)#" index="tagname">
    <cfset tag = getTagData(namespace, tagname) />

    <cfif not structkeyExists(bodies, tag.bodyType)>
        <cfset bodies[tag.bodyType] = ArrayNew(1) />
    </cfif>

    <cfset ArrayAppend(bodies[tag.bodyType], tagname)>


</cfloop>


<cfoutput>
    <table>
        <tr>
            <cfloop list="#structKeyList(bodies)#" index="key">
                <th>#key# end tag</th>
                <cfif ArrayLen(bodies[key]) GT maxLength>
                    <cfset maxLength = ArrayLen(bodies[key])>
                </cfif>
                <cfset ArraySort(bodies[key], "text", "asc")> 
            </cfloop>


            <cfloop from="1" to="#maxLength#" index="i">
                <tr>
                    <cfloop list="#structKeyList(bodies)#" index="key">
                        <td>
                            <cfif ArrayLen(bodies[key]) GTE i>
                                #bodies[key][i]#
                            <cfelse>
                                &nbsp;
                            </cfif>
                        </td>
                    </cfloop>
                </tr>
            </cfloop>
        </tr>
    </table>
</cfoutput>
```

**Comment by prettydiff** [comment]
Sorry for the delay, but I am finally engaged on this issue.  I am looking at the latest documentation at: https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tag-summary.html

I have noticed some minor differences

Tags mentioned in this list that do not appear in the Adobe documentation:
* _
* authenticate
* forward
* graph
* graphdata
* htmlbody
* mapitem
* module
* pageencoding
* retry
* servlet
* servletparam
* sleep
* static
* stopwatch
* video
* videoplayer
* while
* x_

Tags that appear in the documentation but not in this list:
* calendar
* client
* clientsettings
* exchangecalendar
* exchangeconnection
* exchangecontact
* exchangeconversation
* exchangefolder
* exchangefilter
* exchangemail
* exchangetask
* fileupload
* formgroup
* formitem
* grid
* gridcolumn
* gridrow
* gridupdate
* htmltopdfcfhtmltopdf
* htmltopdfitem
* lock
* mapfilter
* mediaplayer
* menu
* menuitem
* messagebox
* NTauthenticate
* oauth
* pdfform
* pdfformparam
* pdfsubform
* pod
* presentation
* presentationslide
* presenter
* print
* progressbar
* report
* reportparam
* sharepoint
* spreadsheet
* sprydataset
* textarea
* tooltip
* tree
* treeitem
* websocket

**Comment by finalcut** [comment]
I'm curious about the absense of cfmodule.  That is a pretty long standing tag that I've used quite a bit.  

* _ - I thought that one seemed odd.  It's probably lucee specific as I had to use LUCEE to extract the data I provided you.  Adobe doesn't really provide useful info on the tags anywhere.
* CFAUTHENTICATE - a now obsolete tag
* CFFORWARD - I think this is something other CF engines implemented.  Works like CFLOCATION but does the redirect on the server instead of in the client.
* CFGRAPH - deprecated but existed in CF9 and maybe 10?
* CFGRAPHDATA - child of CFGRAPH also deprecated
* CFHTMLBODY - something from other CF engines (lucee, openBD etc)
* CFMAPITEM - this is a valid [CF tag](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-m-o/cfmapitem.html) and is on the page you linked.  It's a child of CFMAP
* CFMODULE - I don't know why this isn't on the page but it is [a valid cf tag](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-m-o/cfmodule.html) and I use it all the time.
* CFPAGEENCODING - probably just from alternate CF engines like Lucee, Railo, and OpenBD
* CFRETRY - probably just from alternate CF engines like Lucee, Railo, and OpenBD
* CFSERVLET - is no longer supported. I think it was deprecated in CF9.
* CFSERVELETPARM - child of CFSERVELT also deprecated
* CFSLEEP - I've used this tag before; it's use to put a thread on pause.  This tag can not have a body.  There is still a cf script function called "sleep"   - i believe CFSLEEP was introduced in CF8; not sure when it might have been removed (or why).  It may never have been an "official" tag.
* CFSTATIC - probably just from alternate CF engines like Lucee, Railo, and OpenBD
* CFSTOPWATCH - probably just from alternate CF engines like Lucee, Railo, and OpenBD;
* CFVIDEO - probably just from alternate CF engines like Lucee, Railo, and OpenBD
* CFVIDEOPLAYER - probably just from alternate CF engines like Lucee, Railo, and OpenBD
* CFWHILE - probably just from alternate CF engines like Lucee, Railo, and OpenBD
* CFX_ - This might be a reference to all CFX tags which are [written in C++ or Java](https://helpx.adobe.com/coldfusion/cfml-reference/topics/coldfusion-cfx-reference.html) and then included via special thing in the cf administrator.


That second list is pretty long. I'll revisit that later.

**Comment by prettydiff** [comment]
Thanks for the quick update.  I will work with this so far and I will let you know when I have something to play with.

**Comment by finalcut** [comment]
I've updated [the spreadsheet](https://docs.google.com/spreadsheets/d/1Sr-4kYgRI6WV6PJShtvjvyP4VhVM8ONvHk95MyRjiGw/edit?usp=sharing) with some new columns to address the missing tags you mentioned.

One change is that you had `mapfilter` and it is actually `imapfilter`

As I didn't have an automatic programattic way of getting these I basically just read the documentation and, when unsure, wrote some code using the tag in various ways to see if the end tag was required or not.

**Comment by prettydiff** [comment]
Awesome,  I am mostly complete with the prior list.  I will put in these additions and let you know.

**Comment by finalcut** [comment]
sweet. thanks. If I can offer any other assistance let me know.

On Fri, Dec 4, 2015 at 4:34 PM Austin Cheney <notifications@github.com>
wrote:

> Awesome, I am mostly complete with the prior list. I will put in these
> additions and let you know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prettydiff/prettydiff/issues/158#issuecomment-162087733>
> .
>
-- 
Bill

**Comment by prettydiff** [comment]
I have added support for the original list (except for cf_ tags) at http://prettydiff.com/ignore/testlocation/index.xhtml?m=beautify

I will add in the additional tags soon.  In the mean time let's see if I am mutilating code or curating it correctly.

**Comment by finalcut** [comment]
Ill run a variety of code through this by Monday. I'll let you know what
happens.

On Sat, Dec 5, 2015, 00:12 Austin Cheney <notifications@github.com> wrote:

> I have added support for the original list (except for cf_ tags) at
> http://prettydiff.com/ignore/testlocation/index.xhtml?m=beautify
>
> I will add in the additional tags soon. In the mean time let's see if I am
> mutilating code or curating it correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prettydiff/prettydiff/issues/158#issuecomment-162141497>
> .
>
-- 
Bill

**Comment by prettydiff** [comment]
I just included the latest lists in the spreadsheet into the code at the mentioned online experiment location: http://prettydiff.com/ignore/testlocation/index.xhtml?m=beautify

**Comment by finalcut** [comment]
We're either in vastly different time zones or you work late hours.  Thanks
for the update.  I'll try to put together a good corpus of tests

On Sun, Dec 6, 2015, 00:52 Austin Cheney <notifications@github.com> wrote:

> I just included the latest lists in the spreadsheet into the code at the
> mentioned online experiment location:
> http://prettydiff.com/ignore/testlocation/index.xhtml?m=beautify
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prettydiff/prettydiff/issues/158#issuecomment-162274843>
> .
>
-- 
Bill

**Comment by finalcut** [comment]
so far, looking at it very quickly one bug pops out.

If  I have a line of code like this:

```cfm
<cfif x EQ 1
OR y EQ 2>
    <cfset z = 3 />
</cfif>    
```

The beautifier changes it to:

```cfm
            <cfif 1 2 EQ EQ OR x y>
                <cfset z=3/>
            </cfif>
```


For a more clear example 
```
<CFIF ListLen(Attributes.Site_Type_ID)
OR ListLen(Attributes.Class_Type_ID)
OR Attributes.Grantee_ID
OR Attributes.Resa_ID
OR Attributes.Class_Site_ID
OR Attributes.Class_ID
OR Attributes.NotComplete>
...
```

becomes:

```
                    <CFIF
                        Attributes.Class_ID
                        Attributes.Class_Site_ID
                        Attributes.Grantee_ID
                        Attributes.NotComplete
                        Attributes.Resa_ID
                        ListLen(Attributes.Class_Type_ID)
                        ListLen(Attributes.Site_Type_ID)
                        OR
                        OR
                        OR
                        OR
                        OR
                        OR>
```

The indentation is perfect but the reorganization of the `IF` statement is obviously no good.

**Comment by finalcut** [comment]
another small problem:

```cfm
<CFMODULE	Template="../../common/capture_content.cfm" ReturnVariable="displayContent">
<CFIF Len(FileName)>
<CFSET Caption="Mailing Labels Created">
<div>
<CFOUTPUT><a href="profdev/display/#fileName#">Download Mailing Labels</a></CFOUTPUT>
</div>
<p>
To save this file right click on the link above and choose "Save Target As..."
</p>
<p>
If you would like a coversheet for these labels that describes how they were filtered then
<CFSET formParams = "mailtype=#Attributes.MailType#">
<cfif isdefined("form.fieldnames")>
<cfloop list="#form.fieldnames#" index="field">
<cfset formParams = ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
</cfloop>
</cfif>
<CF_AEMIS_PRINT
Caption	="Load the Coversheet"
pURL	="index.cfm?Section=#request.site.Section#&Page=#request.site.Page#&Step=CoverSheet&#formParams#"
Image	="">
<p>
To use these labels, open the file in Microsoft Word and print them.
</p>
<p class="warning">It is always a good idea to print one test page
on plain paper and overlay it on your labels before printing the entire list to make sure everything is configured on your printer
correctly.
</p>
<p>
Mailing Labels are formatted for standard Avery 5160 mailing label stock.
</p>
<CFELSE>
<CFSET Caption="Mailing Label Creation Error">
There were no people found that match your filter criteria. Please go back to the filter and try again.
</CFIF>
</CFMODULE>
```

generates:

```cfm
            <CFMODULE
                ReturnVariable="displayContent"
                Template="../../common/capture_content.cfm">
            <CFIF Len(FileName)>
                <CFSET Caption="Mailing Labels Created">
                <div>
                    <CFOUTPUT>
                        <a href="profdev/display/#fileName#">
                            Download Mailing Labels
                        </a>
                    </CFOUTPUT>
                </div>
                <p>
                    To save this file right click on the link above and choose "Save Target As..."
                </p>
                <p>
                    If you would like a coversheet for these labels that describes how they were
                    filtered then
                    <CFSET formParams="mailtype=#Attributes.MailType#">
                    <cfif ) isdefined("form.fieldnames">
                        <cfloop index="field" list="#form.fieldnames#">
                            <cfset
                                "#field#="
                                &
                                &"#field#"
                                )
                                ),"&"
                                evaluate("form."
                                formParams=ListAppend(formParams,>
                        </cfloop>
                    </cfif>
                    <CF_AEMIS_PRINT
                        Caption="Load the Coversheet"
                        Image=""
                        pURL="index.cfm?Section=#request.site.Section#&Page=#request.site.Page#&Step=CoverSheet&#formParams#">
                        <p>
                            To use these labels, open the file in Microsoft Word and print them.
                        </p>
                        <p class="warning">
                            It is always a good idea to print one test page on plain paper and overlay it on
                            your labels before printing the entire list to make sure everything is
                            configured on your printer correctly.
                        </p>
                        <p>
                            Mailing Labels are formatted for standard Avery 5160 mailing label stock.
                        </p>
                    <CFELSE>
                        <CFSET Caption="Mailing Label Creation Error">
                        There were no people found that match your filter criteria. Please go back to
                        the filter and try again.
                    </CFIF>
                </CFMODULE>
```

The indentation of the <cfif> immediately following the cfmodule call is not indented properly and thus the closing /cfmodule is overly indented


Also:
```cfm
<CFIF addresses.recordCount>
<CF_AEMIS_MAILING_LABELS
Directory		="#ThisDir#"
Addresses		="#addresses#"
ReturnVariable	="fileName">
</CFIF>
```

generates:
```cfm
            <CFIF addresses.recordCount>
                <CF_AEMIS_MAILING_LABELS
                    Addresses="#addresses#"
                    Directory="#ThisDir#"
                    ReturnVariable="fileName"></CFIF>
```

The closing cfif tag is in a weird place. 

I assume both of these are probably related to the presensence of a custom tag (CF_) in between the tags and, as you stated, you aren't dealing with custom tags at all.

I can say that all <CF_ tags are optionally closed.  Adding a closing tag to a <CF_ tag actually has an impact on the behavior of the tag (it is executed once on tag open and a second time on tag close. So many <CF_ tags have logic like this within them:

```cfm
<cfif thisTag.exectutionMode EQ "start">
... custom tag logic goes here...
</cfif>
```

**Comment by prettydiff** [comment]
* I have added the tag names `cfif` and `cfelseif` to the omit list for attribute sorting, so that problem is solved.
* tag names starting with `cf_` are now self-closing tags.

The code is updated.  Please test again.

http://prettydiff.com/ignore/testlocation/index.xhtml?m=beautify

**Comment by finalcut** [comment]
It looks much better; especially the cfif's

There is still a minor indentation problem within the ```<CFMODULE.``` call

```cfm
<CFMODULE Template="../../common/my_module.cfm" ReturnVariable="someVariable"><CFIF Len(FileName)>
do some stuff since it is true
<CFELSE>
do some other stuff since it is false
</CFIF>
</CFMODULE>
```

generates:

```cfm
<CFMODULE ReturnVariable="someVariable" Template="../../common/my_module.cfm">
<CFIF Len(FileName)>
    do some stuff since it is true
<CFELSE>
    do some other stuff since it is false
</CFIF>
</CFMODULE>
```

You'll notice the `<CFIF>` is not indented within the `<CFMODULE>`  the `<CFMODULE>` is the parent tag here and thus the code within it should be indented.

There is actually a similar issue with a `<cfloop>` embedded within a `<cfif>` as shown here:

```cfm
<cfif isdefined("form.fieldnames")>
<cfloop list="#form.fieldnames#" index="field">
<cfset formParams = ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
</cfloop>
</cfif>
```
generates:
```cfm
<cfif isdefined("form.fieldnames" )>
<cfloop index="field" list="#form.fieldnames#">
    <cfset
        "#field#="
        &
        &"#field#"
        )
        ),"&"
        evaluate("form."
        formParams=ListAppend(formParams,>
</cfloop>
</cfif>
```

The `cfset` line getting broken up seems very strange to me.  And the lack of indentation of the `cfloop` within the `cfif`


Now that I mention it the `cfset` is a real issue.  Here is another example of how cfset is being broken:  I'm not exactly sure what happened:

source:

```cfm
<cfset links = "<p><a href=""index.cfm?Section=#request.site.Section#&Page=#request.site.Page#&Step=#LastStep#&#formParams#&TimeStamp=#request.site.TimeStamp#"">Generate</a> another set of #captionText# mailing labels</p>">
```

result
```cfm
<cfset
"
"index.cfm?Section=#request.site.Section#&Page=#request.site.Page#&Step=#LastStep#&#formParams#&TimeStamp=#request.site.TimeStamp#"
links="<p><a href=">
Generate
</a>
another set of #captionText# mailing labels
</p>
">
```

In this case the variable `Links` is being lost and the entire string is mangled.

`cfset` is basically just an ugly way of setting variable values of the syntax:

`<cfset var = value />` or `<cfset var = value>`

Sometimes the `value` could be a complex expression but it shouldn't be parsed by the beautifier at all.

**Comment by prettydiff** [comment]
Fixed.  Sorry about that.  I have a valid solution in place for optional end tags.  I just presume that they are a self-closing tag until I get to an end tag with a name in the *optional* or *prohibited* categories and then I change the self-closing tag into a start tag.  My problem is that this valid solution was expecting a lowercase name for comparison.

**Comment by finalcut** [comment]
makes sense; I'm just using as ugly of cf code as I can.

**Comment by finalcut** [comment]
The indentation is now right.  great job.  The `<cfset ` stuff is still broken though.

```cfm
<cfset formParams = ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
```
generates

```cfm
<cfset
            "#field#="
            &
            &"#field#"
            )
            ),"&"
            evaluate("form."
            formParams=ListAppend(formParams,>
```

and the other one I previously identified.  The variable is lost and the value is mangled.

**Comment by prettydiff** [comment]
I was mutilating that attribute by not considering the `(` and `)` as delimiters and from the spaces around the equal sign.  This is all corrected now.

**Comment by finalcut** [comment]
I'm having some issues with the test site; when I paste in (or open a file) it is injecting a bunch of `>` at the beginning of lines.. The beautifier doesn't have a chance with all those extra `>` sitting around

**Comment by finalcut** [comment]
However, if I just put this one line of code in there:

```cfm
<CFSET Links = "<p><a href=""index.cfm?Section=#request.site.Section#&Page=#request.site.Page#&Step=#LastStep#&#formParams#&TimeStamp=#request.site.TimeStamp#"">Generate</a> another set of #captionText# mailing labels</p>">
```

it still mangles it. I end up with 

```cfm
<CFSET
    "
    "index.cfm?Section=#request.site.Section#&Page=#request.site.Page#&Step=#LastStep#&#formParams#&TimeStamp=#request.site.TimeStamp#"
    Links="<p><a href=">
Generate
</a>
another set of #captionText# mailing labels
</p>
```

**Comment by finalcut** [comment]
Also this small block gets pretty messed up still:

```cfm
<cfif isdefined("form.fieldnames")>
				<cfloop list="#form.fieldnames#" index="field">
					<cfset formParams = ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
				</cfloop>
			</cfif>
```

though the `cfset` is perfect there seems to be a bunch of extra `>` at the end..

```cfm
<cfif
    isdefined("form.fieldnames")
    >
    <cfloop list="#form.fieldnames#" index="field">
    <cfset formParams = ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
    </cfloop>
    </cfif>				
					
				
			
```

Interestingly, when I copy paste the output I'm not getting the extra `>` values but in the tester they are showing up.  I'm not sure what is going on.  I wonder if all the extra `>` are how the editor/tester is showing tabs/indentation or something.  It's very strange.

**Comment by prettydiff** [comment]
It could be some problem I am not aware of with the Ace code editor.  There is an option if you scroll down just a bit to turn off the Ace code editor.

It might be easier to just run from the command line.  Just:

    npm install prettydiff
    cd node_modules/prettydiff/lib

Then overwrite the local markuppretty.js file with the one at http://prettydiff.com/ignore/testlocation/lib/markuppretty.js

I am looking at this code:

    <CFSET Links = "<p><a href=""index.cfm?Section=#request.site.Section#&Page=#request.site.Page#&Step=#LastStep#&#formParams#&TimeStamp=#request.site.TimeStamp#"">Generate</a> another set of #captionText# mailing labels</p>">

The problem is the `""` following `href=` and then later the `""` following `TimeStamp#`.  This looks like closing and immediately reopening quotes.  Even if I fixed the parser to produce less broken output you would still end up with effectively 4 attributes instead of one.  If I change those to single quotes there is no longer any problem.  Is this valid code?

The last code example is fixed though.

**Comment by finalcut** [comment]
Yeah it's valid but ugly code. To escape quotes inside quotes you double
them.  So """" is a valid way to put a single double quite inside a double
quoted string.

Likewise '''' is how you put a single quite inside a single quoted string.

On Mon, Dec 7, 2015, 16:47 Austin Cheney <notifications@github.com> wrote:

> It could be some problem I am not aware of with the Ace code editor. There
> is an option if you scroll down just a bit to turn off the Ace code editor.
>
> It might be easier to just run from the command line. Just:
>
> npm install prettydiff
> cd node_modules/prettydiff/lib
>
> Then overwrite the local markuppretty.js file with the one at
> http://prettydiff.com/ignore/testlocation/lib/markuppretty.js
>
> I am looking at this code:
>
> <CFSET Links = "<p><a href=""index.cfm?Section=#request.site.Section#&Page=#request.site.Page#&Step=#LastStep#&#formParams#&TimeStamp=#request.site.TimeStamp#"">Generate</a> another set of #captionText# mailing labels</p>">
>
> The problem is the "" following href= and then later the "" following
> TimeStamp#. This looks like closing and immediately reopening quotes.
> Even if I fixed the parser to produce less broken output you would still
> end up with effectively 4 attributes instead of one. If I change those to
> single quotes there is no longer any problem. Is this valid code?
>
> The last code example is fixed though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prettydiff/prettydiff/issues/158#issuecomment-162674873>
> .
>
-- 
Bill

**Comment by prettydiff** [comment]
Fixed the quote issue.

**Comment by finalcut** [comment]
Cool. I'll grab the npm later tonight and run some more tests

On Mon, Dec 7, 2015, 17:35 Austin Cheney <notifications@github.com> wrote:

> Fixed the quote issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prettydiff/prettydiff/issues/158#issuecomment-162690428>
> .
>
-- 
Bill

**Comment by finalcut** [comment]
It's looking pretty good.  The only strange behavior I'm seeing at the moment is an extra line break in some `<CFSET` code like so:

SOURCE:
```cfm
			<cfif isdefined("form.fieldnames")>
				<cfloop list="#form.fieldnames#" index="field">
					<cfset formParams = ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
				</cfloop>
			</cfif>
```

results:
```cfm
<CFSET formParams="mailtype=#Attributes.MailType#">
<cfif isdefined("form.fieldnames")>
    <cfloop index="field" list="#form.fieldnames#">
        <cfset
            formParams=ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
    </cfloop>
</cfif>

```

The `cfset` in the middle there should not be broken to a different line.  It happens even if that cfset line is NOT a child. For instance if I have a simple cfm file with just this in it:

```cfm
<cfset formParams = ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
```

results:

```cfm
<cfset
    formParams=ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
```


I ran these from the command line as you had suggested.

**Comment by finalcut** [comment]
here is another weird `cfset` issue

```cfm
	<cfset reportCount = reportCount + 1 />
```

becomes

```cfm
    <cfset + 1 reportCount=reportCount/>
```


plus some weirdness you may not want to hear/see sorry.

So this is perfectly valid CFML

```cfm
	<div <cfif reportCount NEQ ListLen(reportList)>class="paged"</cfif>>
```

as you might imagine the beautifier runs into some trouble there:

```cfm
    <div class=paged"</cfi <cfif reportCount NEQ ListLen(reportList)>>>
```


The only other thing I've seen that is coming out funny (but isn't a breaking change) is; on long lines (greater than 80 characters) it puts in some extra line breaks:


Here is an example at 80:

```cfm
<CFIF (Attributes.X OR (Attributes.Value12 EQ SOME_VALUE)) AND NOT Attributes.Z>
</CFIF>
```

it is left alone and the result == source.  But at 81:

```cfm
<CFIF (Attributes.X OR (Attributes.Value123 EQ SOME_VALUE)) AND NOT Attributes.Z>
</CFIF>
```

It turns into:

```cfm
<CFIF
    (Attributes.X OR (Attributes.Value123 EQ SOME_VALUE))
    AND
    NOT
    Attributes.Z>
</CFIF>
```

**Comment by prettydiff** [comment]
The problem with the 80 character width is the option `wrap` that by default has a value of 80.  You can change this to 0 to prevent wrapping in the options further down the page or by adding the following code anywhere in a given code sample:

    

I fixed the defect associated with the embedded CF tag in the div tag.  The sample is a bit defective though in that the div tag should have a closing div tag.

**Comment by finalcut** [comment]
yeah, I didn't include all the crap after the opening div tag or the close; I just wanted you to see an example.  I'll re-grab your .js file and try it some more.  Thanks for this.

**Comment by prettydiff** [comment]
No, thank you.  I couldn't do this without your assistance.

**Comment by finalcut** [comment]
Everything looks pretty good with just one remaining issue - the breaking of `<cfset` into multiple lines unnecessarily.

In fact, I'd think `cfset` should never break into multiple lines.

I tried this as the source: 
```cfm
<!--prettydiff.com wrap:0-->
<cfset formParams=ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
```

and the result was:

```cfm
<!--prettydiff.com wrap:0-->
<cfset
    formParams=ListAppend(formParams, "#field#=" & evaluate("form."&"#field#"),"&")>
```

I'll look for some other good chunks of code to test with later (maybe tonight or tomorrow).

**Comment by prettydiff** [comment]
Text/attribute wrapping will never again be applied to `cfset` tags.

**Comment by finalcut** [comment]
awesome.  I'll find a more comprehensive corpus and let you know.

**Comment by finalcut** [comment]
Hi, I've found another issue.

code within cfscript tags should not be beautified OR else be beautified with a different set of rules.

The following code becomes invalid when beautified:

```cfm
<cfscript>
  /**
  * Calculate a CRC-16 checksum for a string. CRC should not be used
  * for encryption, but may be suitable for data validation purposes.
  *
  * This ColdFusion function is based on a JavaScript function found
  * at this URL: HTTP://WWW.digsys.se/JS_crc.HTML . The following
  * notice is required by the authors of the original function:
  *
  * Copyright (c) 1989 AnDan Software. You may use this program, or
  * code or tables extracted from it, as long as this notice is not
  * removed or changed.
  *
  * @param str              string (Required)
  * @return a string representing a hexadecimal number between 0000
  * and FFFF
  * @author Matthew Walker, .eswsoftware.com
  * @version 1, 2004-06-28
  */

  function crc16(str) {

    var Crc16Tab = listToArray('0,4129,8258,12387,16516,20645,24774,28903,33032,37161,41290,45419,49548,53677,57806,61935,4657,528,12915,8786,21173,17044,29431,25302,37689,33560,45947,41818,54205,50076,62463,58334,9314,13379,1056,5121,25830,29895,17572,21637,42346,46411,34088,38153,58862,62927,50604,54669,13907,9842,5649,1584,30423,26358,22165,18100,46939,42874,38681,34616,63455,59390,55197,51132,18628,22757,26758,30887,2112,6241,10242,14371,51660,55789,59790,63919,35144,39273,43274,47403,23285,19156,31415,27286,6769,2640,14899,10770,56317,52188,64447,60318,39801,35672,47931,43802,27814,31879,19684,23749,11298,15363,3168,7233,60846,64911,52716,56781,44330,48395,36200,40265,32407,28342,24277,20212,15891,11826,7761,3696,65439,61374,57309,53244,48923,44858,40793,36728,37256,33193,45514,41451,53516,49453,61774,57711,4224,161,12482,8419,20484,16421,28742,24679,33721,37784,41979,46042,49981,54044,58239,62302,689,4752,8947,13010,16949,21012,25207,29270,46570,42443,38312,34185,62830,58703,54572,50445,13538,9411,5280,1153,29798,25671,21540,17413,42971,47098,34713,38840,59231,63358,50973,55100,9939,14066,1681,5808,26199,30326,17941,22068,55628,51565,63758,59695,39368,35305,47498,43435,22596,18533,30726,26663,6336,2273,14466,10403,52093,56156,60223,64286,35833,39896,43963,48026,19061,23124,27191,31254,2801,6864,10931,14994,64814,60687,56684,52557,48554,44427,40424,36297,31782,27655,23652,19525,15522,11395,7392,3265,61215,65342,53085,57212,44955,49082,36825,40952,28183,32310,20053,24180,11923,16050,3793,7920');
    
    var n = 1;
    var length=len(str);
    var crc = 0;
    var ch = "";
    
    if ( not structKeyExists(request, "eswsoftware") )
      request.eswsoftware = structNew();
    if ( not structKeyExists(request.eswsoftware, "crc16") )
      request.eswsoftware.crc16 = structNew();  
    request.eswsoftware.crc16.version = 1;

    for ( ; n lte length ; n = n + 1 ) {
      ch = mid(str, n, 1);
            
      crc = bitAnd(
        bitXor( 
          bitShlN(crc, 8),
          Crc16Tab[
            1
            + bitAnd(
              bitXor(
                bitShrN(crc, 8),
                asc(ch)
              ),
              255
            )
          ]
        ),
      65535);
    }
    return formatBaseN(crc, 16);

  }
</cfscript>
```

it becomes:

```cfm
<cfscript>
    /** * Calculate a CRC-16 checksum for a string. CRC should not be used * for
    encryption, but may be suitable for data validation purposes. * * This
    ColdFusion function is based on a JavaScript function found * at this URL:
    HTTP://WWW.digsys.se/JS_crc.HTML . The following * notice is required by the
    authors of the original function: * * Copyright (c) 1989 AnDan Software. You may
    use this program, or * code or tables extracted from it, as long as this notice
    is not * removed or changed. * * @param str string (Required) * @return a string
    representing a hexadecimal number between 0000 * and FFFF * @author Matthew
    Walker, .eswsoftware.com * @version 1, 2004-06-28 */ function crc16(str) { var
    Crc16Tab =
    listToArray('0,4129,8258,12387,16516,20645,24774,28903,33032,37161,41290,45419,49548,53677,57806,61935,4657,528,12915,8786,21173,17044,29431,25302,37689,33560,45947,41818,54205,50076,62463,58334,9314,13379,1056,5121,25830,29895,17572,21637,42346,46411,34088,38153,58862,62927,50604,54669,13907,9842,5649,1584,30423,26358,22165,18100,46939,42874,38681,34616,63455,59390,55197,51132,18628,22757,26758,30887,2112,6241,10242,14371,51660,55789,59790,63919,35144,39273,43274,47403,23285,19156,31415,27286,6769,2640,14899,10770,56317,52188,64447,60318,39801,35672,47931,43802,27814,31879,19684,23749,11298,15363,3168,7233,60846,64911,52716,56781,44330,48395,36200,40265,32407,28342,24277,20212,15891,11826,7761,3696,65439,61374,57309,53244,48923,44858,40793,36728,37256,33193,45514,41451,53516,49453,61774,57711,4224,161,12482,8419,20484,16421,28742,24679,33721,37784,41979,46042,49981,54044,58239,62302,689,4752,8947,13010,16949,21012,25207,29270,46570,42443,38312,34185,62830,58703,54572,50445,13538,9411,5280,1153,29798,25671,21540,17413,42971,47098,34713,38840,59231,63358,50973,55100,9939,14066,1681,5808,26199,30326,17941,22068,55628,51565,63758,59695,39368,35305,47498,43435,22596,18533,30726,26663,6336,2273,14466,10403,52093,56156,60223,64286,35833,39896,43963,48026,19061,23124,27191,31254,2801,6864,10931,14994,64814,60687,56684,52557,48554,44427,40424,36297,31782,27655,23652,19525,15522,11395,7392,3265,61215,65342,53085,57212,44955,49082,36825,40952,28183,32310,20053,24180,11923,16050,3793,7920');
    var n = 1; var length=len(str); var crc = 0; var ch = ""; if ( not
    structKeyExists(request, "eswsoftware") ) request.eswsoftware = structNew(); if
    ( not structKeyExists(request.eswsoftware, "crc16") ) request.eswsoftware.crc16
    = structNew(); request.eswsoftware.crc16.version = 1; for ( ; n lte length ; n =
    n + 1 ) { ch = mid(str, n, 1); crc = bitAnd( bitXor( bitShlN(crc, 8), Crc16Tab[
    1 + bitAnd( bitXor( bitShrN(crc, 8), asc(ch) ), 255 ) ] ), 65535); } return
    formatBaseN(crc, 16); }
</cfscript>
```

**Comment by finalcut** [comment]
I would probably encourage you to NOT use line wrapping at all within <cfquery> tags

Simply becuase things like:
```cfm
			<cfquery name="qVesselExists" datasource="#getDSN()#">
				SELECT vessel_code
				FROM master_vessel
				WHERE REGEXP_REPLACE(regexp_replace(vessel_long_name, '( *[[:punct:]])', ''), '\s*', '') = <CFQUERYPARAM CFSQLType="CF_SQL_Varchar" Value="#condensedVesselText#">
				AND operator_code = <CFQUERYPARAM CFSQLType="CF_SQL_Integer" Value="#Arguments.OperatorCode#" />
			</cfquery>
```

Become:

```cfm
                <cfquery datasource="#getDSN()#" name="qVesselExists">
                    SELECT vessel_code FROM master_vessel WHERE
                    REGEXP_REPLACE(regexp_replace(vessel_long_name, '( *[[:punct:]])', ''), '\s*',
                    '') =
                    <CFQUERYPARAM CFSQLType="CF_SQL_Varchar" Value="#condensedVesselText#">
                    AND operator_code =
                    <CFQUERYPARAM CFSQLType="CF_SQL_Integer" Value="#Arguments.OperatorCode#"/>
                </cfquery>
```

and having the cfqueryparam wrap to the next line makes the code less readable.

**Comment by finalcut** [comment]
Also (sorry for the surge).. I'd treat `<cfreturn` like you did `<cfset` and not line-wrap that ever as well:

```cfm
		<cfreturn variables.instance.coderFactory.getCoder("dataset","#arguments.datasetID#") />
```
becomes

```cfm
        <cfreturn
            variables.instance.coderFactory.getCoder("dataset","#arguments.datasetID#")/>
```

**Comment by finalcut** [comment]
just a question: are you reordering attributes alphabetically.

For instance I notice:

```cfm
	<CFLOOP List="#Arguments.Dataset_ID#" Index="CurDataset">
```

becomes

```cfm
        <CFLOOP Index="CurDataset" List="#Arguments.Dataset_ID#">
```

*note: this tags attribute re-ordering "feels" wrong to me*

and 

```cfm
		<CFQUERY Name="qLines" Datasource="#getDSN()#">
```

becomes

```cfm
            <CFQUERY Datasource="#getDSN()#" Name="qDataset">
```

*note: this attribute reordering doesn't "feel" bad to me*

Honestly, attribute ordering isn't a standard; they are attributes after all and can go in any order.  But I think there are pretty "common" ways of ordering them that most people probably follow and re-ordering them might be viewed as a real negative by some people.

**Comment by prettydiff** [comment]
Updated!

* CFQUERY is now treated like an HTML PRE tag in that all original formatting is preserved as provided.
* CFSCRIPT is now treated like an HTML script tag.  The cfscript is appears to follow slightly different grammars but identical syntax to JavaScript, so I am beautifying this code as JavaScript.
* CFRETURN is now excluded from line wrapping
* I am working on a way to eliminate attribute sorting document-wide using an option: issue #229

**Comment by finalcut** [comment]
updated and 


see some weird indentation going on with cffunctions:

```cfm
	<CFFUNCTION Name="FixDatasetForLine" output="false">
		<CFARGUMENT Name="Line_ID" 		Type="String" 	Required="True">

		<cfset var l = structNew() />


		<cfquery name="l.cinfo" datasource="#getDSN()#">
			SELECT d.id as dataset_id, d.period, l.receiving_date FROM line_container l, dataset_container d
			WHERE l.id = <cfqueryparam cfsqltype="cf_sql_integer" value="#arguments.line_id#" />
			AND d.id = l.dataset_id
		</cfquery>
		<cfset l.true_period = "1/#Month(l.cinfo.receiving_date)#/#Year(l.cinfo.receiving_date)#" />
 		<cfreturn l />
	</CFFUNCTION>





	<CFFUNCTION Name="GetByLineID" access="public" output="false" returntype="struct">
		<cfargument name="ContainerLineID"	type="numeric"	required="true" />
		<cfset var qD = "" />
		<cfquery name="qD" datasource="#getDSN()#">
			SELECT	d.*
		   FROM		line_container 	l,
					dataset_container d
		  WHERE	l.dataset_container_id	= d.id
			AND	l.id 					= <CFQUERYPARAM CFSQLType="CF_SQL_Integer" Value="#arguments.ContainerLineID#">

		</cfquery>
		<cfset qd = ConvertQueryToArray(qd) />

		<cfreturn qd[1] />
	</CFFUNCTION>
```

became:

```cfm
	<CFFUNCTION Name="FixDatasetForLine" output="false">
		<CFARGUMENT Name="Line_ID" 		Type="String" 	Required="True">

		<cfset var l = structNew() />


		<cfquery name="l.cinfo" datasource="#getDSN()#">
			SELECT d.id as dataset_id, d.period, l.receiving_date FROM line_container l, dataset_container d
			WHERE l.id = <cfqueryparam cfsqltype="cf_sql_integer" value="#arguments.line_id#" />
			AND d.id = l.dataset_id
		</cfquery>
        <cfset l.true_period="1/#Month(l.cinfo.receiving_date)#/#Year(l.cinfo.receiving_date)#"/>
            <cfreturn l/>
            </CFFUNCTION>

        <CFFUNCTION
            Name="GetByLineID"
            access="public"
            output="false"
            returntype="struct">
        <cfargument name="ContainerLineID" required="true" type="numeric"/>
            <cfset var qD=""/>
            <cfquery name="qD" datasource="#getDSN()#">
			SELECT	d.*
		   FROM		line_container 	l,
					dataset_container d
		  WHERE	l.dataset_container_id	= d.id
			AND	l.id 					= <CFQUERYPARAM CFSQLType="CF_SQL_Integer" Value="#arguments.ContainerLineID#">

		</cfquery>
            <cfset qd=ConvertQueryToArray(qd)/>

            <cfreturn qd[1]/>
                </CFFUNCTION>
```

This odd indentation cascades down further into the file.

It is a new problem introduced by the latest changes; potentially by the "pre-like-nature" of the `<cfquery>` because I notice this example in another file:

```cfm
	<cfquery name="qCRCInfo" datasource="#getDSN()#">
		SELECT MAX(id) as ADDED_ID
		FROM charter_import_crc
	</cfquery>
```

becomes

```cfm
        <cfquery name="qCRCInfo" datasource="#getDSN()#">
		SELECT MAX(id) as ADDED_ID
		FROM charter_import_crc
	</cfquery>
```

**Comment by prettydiff** [comment]
Fixed.  It was absolutely a regression bug related to `cfquery`.  I was pushing two data types for this one tag, when I should have been only pushing one data type per token.

**Comment by finalcut** [comment]
that is a lot better but it's still just a little tiny bit wonky:

```cfm
	<cfquery name="qCRCInfo" datasource="#getDSN()#">
		SELECT MAX(id) as ADDED_ID
		FROM charter_import_crc
	</cfquery>
```

becomes

```cfm
        <cfquery name="qCRCInfo" datasource="#getDSN()#">
		SELECT MAX(id) as ADDED_ID
		FROM charter_import_crc
	</cfquery>
```

the indentation of the opening 'cfquery' is correct but everything else needs to right shift  by a tab.

This is consistent in all cfquery examples I'm trying.

**Comment by prettydiff** [comment]
Yeah, I need to come up with a better solution that reformats the indentation at the start of all internal lines.  The indentation on the opening tag is correct, because it is actually being processed by the application.  Everything inside the cfquery tag is retained as is verbatim.

**Comment by finalcut** [comment]
I just found another slight but breaking problem:

```cfm
			<cfset getContainerCoder().CheckLine(line_id) />
			<cfset getContainerCoder().CrossCheckLine(line_id) />
```

becomes

```cfm
			<cfset getContainerCoder() .CheckLine(line_id)/>
			<cfset getContainerCoder() .CrossCheckLine(line_id)/>
```

note the whitespace after the `function() ` before the `.secondfunction(arg)`

**Comment by prettydiff** [comment]
I created a new data type to account for cfquery as I expect this kind of formatting problem to be something potentially reoccurring.  The contents of the cfquery tag are now completely preserved aside from indentation at the start of each line.  The beginning of each line is beautified up to the first non-white space character or character string defining a step of indentation.

I have also created these files for unit testing from this issue:

* http://prettydiff.com/test/samples_correct/beautification_markup_cfml.txt
* http://prettydiff.com/test/samples_raw/beautification_markup_cfml.txt

You can run unit tests from the command line if you enter the prettydiff NPM directory and type:

    npm test

**Comment by finalcut** [comment]
that worked great; cfquery is looking good and so is method chaining.  I'll see if I can find some other odd stuff to test with but I'm feeling pretty good about it at the moment.

**Comment by finalcut** [comment]
Okay, I have a new problem for you sadly.  This also is related to `CFQUERY` but only occurs if `CFQUERY` has tag children such as `CFIF`


Here is the source code:

```cfm
<cfcomponent extends="BaseComponent">

	<cffunction name="GetAll" output="false" returntype="query">
		<cfquery name="q" datasource="#getDSN()#">
			SELECT *

		  FROM	foobar
		WHERE	foobarId  = <cfqueryparam cf_sql_integer" value="#arguments.foobarId#">


		  <CFIF LEN(TRIM(arguments.searchString))>
		AND comments LIKE <cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.searchString#" />
		  </CFIF>

		ORDER BY title desc

		</cfquery>

		<cfreturn q />
	</cffunction>

	<cffunction name="CreateFoobar" output="false">
		<cfargument name="foobar" type="any" required="true">

		<cfstoredproc procedure="Foobar.New" datasource="#getDSN()#">
				<cfprocparam cfsqltype="cf_sql_varchar"  dbvarname="pFoobar"	type="in" 	value="#arguments.foobar#">
		</cfstoredproc>
	</cffunction>


	<!--- dependencies --->
	<cffunction name="setDSN" access="public" returntype="void" output="false">
		<cfargument name="dsn"	type="any">
		<cfset variables.instance.dsn= arguments.dsn/>
	</cffunction>
	<cffunction name="getDSN" access="public" returntype="any" output="false">
		<cfreturn variables.instance.dsn/>
	</cffunction>

</cfcomponent>
```

and here is the result:

```cfm
<cfcomponent extends="BaseComponent">

    <cffunction name="GetAll" output="false" returntype="query">
        <cfquery name="q" datasource="#getDSN()#">
            SELECT *

            FROM	foobar
            WHERE	foobarId  = <cfqueryparam cf_sql_integer" value="#arguments.foobarId#">


            <CFIF LEN(TRIM(arguments.searchString))>
            AND comments LIKE <cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.searchString#" />
            </CFIF>

            ORDER BY title desc

            </cfquery>

            <cfreturn q />
            </cffunction>

            <cffunction name="CreateFoobar" output="false">
            <cfargument name="foobar" type="any" required="true">

            <cfstoredproc procedure="Foobar.New" datasource="#getDSN()#">
            <cfprocparam cfsqltype="cf_sql_varchar"  dbvarname="pFoobar"	type="in" 	value="#arguments.foobar#">
            </cfstoredproc>
            </cffunction>


            <!--- dependencies --->
            <cffunction name="setDSN" access="public" returntype="void" output="false">
            <cfargument name="dsn"	type="any">
            <cfset variables.instance.dsn= arguments.dsn/>
            </cffunction>
            <cffunction name="getDSN" access="public" returntype="any" output="false">
            <cfreturn variables.instance.dsn/>
            </cffunction>

            </cfcomponent>
```

If I remove the `cfif` from within the `cfquery` everything beautifies nicely.

**Comment by finalcut** [comment]
It appears my test file had a syntax error in it.  There was a missing attribute on the cfqueryparam.  However, the problem still exists; I'll provide a better sample.

**Comment by finalcut** [comment]
Okay, here is a valid test case that shows the problem.  It appears to be caused by the single tick quote in the comment within the query.  My prior supposition was all wrong.

source:
```cfm
<cfcomponent extends="BaseComponent">
	<cffunction name="GetAll" output="false" returntype="query">
		<cfargument name="SearchString"		type="string" default="" />

		<cfset var q = "" />
		<cfset var local = structNew() />

		<cfquery name="q" datasource="#getDSN()#">
			SELECT *

		  FROM	foobar

		WHERE	1=1

		  <CFIF LEN(TRIM(arguments.searchString))>
			<!--- foo isn't bar --->
			<CFSET arguments.searchString = "%#arguments.searchString#%" />
		AND comments LIKE <cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.searchString#" />
		  </CFIF>

		</cfquery>

		<cfreturn q />
	</cffunction>


	<!--- dependencies --->
	<cffunction name="setMapping" access="public" returntype="void" output="false">
		<cfargument name="mapping"	type="any">
		<cfset variables.instance.mapping = arguments.mapping/>
	</cffunction>
	<cffunction name="getMapping" access="public" returntype="any" output="false">
		<cfreturn variables.instance.mapping />
	</cffunction>

</cfcomponent>
```

result:

```cfm
<cfcomponent extends="BaseComponent">
    <cffunction name="GetAll" output="false" returntype="query">
        <cfargument default="" name="SearchString" type="string"/>

        <cfset var q=""/>
        <cfset var local=structNew()/>

        <cfquery name="q" datasource="#getDSN()#">
            SELECT *

            FROM	foobar

            WHERE	1=1

            <CFIF LEN(TRIM(arguments.searchString))>
            <!--- foo isn't bar --->
            <CFSET arguments.searchString = "%#arguments.searchString#%" />
            AND comments LIKE <cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.searchString#" />
            </CFIF>

            </cfquery>

            <cfreturn q />
            </cffunction>


            <!--- dependencies --->
            <cffunction name="setMapping" access="public" returntype="void" output="false">
            <cfargument name="mapping"	type="any">
            <cfset variables.instance.mapping = arguments.mapping/>
            </cffunction>
            <cffunction name="getMapping" access="public" returntype="any" output="false">
            <cfreturn variables.instance.mapping />
            </cffunction>

            </cfcomponent>
```

If I remove the word `isn't` from the comment of `  everything beautifies fine.

**Comment by finalcut** [comment]
Just a point of reference a coldfusion comment has three hyphens instead of two.

`<!---  ... --->`

cfscript, which you're handling like javascript has the same kind of comment delimiters as JS:

* `//` single line
* `/* ... */`  multiline

**Comment by prettydiff** [comment]
This was the fact that a comment was inside a cfquery block that created the bug... what a great find.  I changed the code that comments are parsed uniquely so that additional logic isn't considered in the case there is ever such a conflict from inside a comment.

In order to parse things like an HTML PRE tag or in this case CFQUERY I am actually cheating a bit and parsing the start tag, all child/descendant nodes, and the end tag into a single token.  This is completely insufficient from the perspective of a formal parser, but it works perfectly for a beautifier at preserving all characters as provided.  Having a quote inside a comment, which is then inside one of these IGNORE type blocks created a conflict that I didn't imagine before, and I have added some logic to ensure this conflict never occurs again.  Eventually I will need to come up with a more complete parsing consideration for code with preserved white space.

I have added recognition for a cf comment, but some second and third order consequences I am thinking about:
* I must recognize the CF comment delimiters, but only in CF documents so that I don't create regression with HTML comments in the case where a comment is opened with three dashes, but closed with two.  I am also searching the document for tags that begin with CF and additional letters just to ensure I am not applying CF comments in non-CF documents.  This solution is far from complete, but should work for more than 99% of use cases, which is probably ok since the problem space is rare itself.
* I imagine there might be a conflict if an HTML comment should contain CF comment.  I will test more on this.

**Comment by finalcut** [comment]
it seems to be working very well now though I do have a contradictory, to our prior, thought you may just ignore simply because it deals with `CFSET` and line wrapping!

Take this code block for example:

```cfm
		<cfset getImportLeasor().CodeAndErrorCheck(argumentCollection = {
				  OrganizationCode	=arguments.organizationCode
				, Leasor_Import_ID	=arguments.FileId
				, organizationList	=organizationList
				, Leasor_ID 		=arguments.leasorID
			}) />
```

The functions arguments, are each on the next line and indented; in this case they are being passed as a structure or map (or dictionary) as denoted by the `{` and `}`

When the beautifer hits this line it gives back:

```cfm
            <cfset getImportLeasor().CodeAndErrorCheck(argumentCollection = { OrganizationCode =arguments.organizationCode , Leasor_Import_ID =arguments.FileId , organizationList =organizationList , foobarCode =arguments.foobarCode , Leasor_ID =local.leasor_id })/>
```


Which is valid but it is less beautiful.


Basically, this map is used to enable the passing of variables by name -vs- position.  When passing by position the map isn't used and something like this would be the normal way of writing it:

```cfm
 <cfset getImportLeasor().CodeAndErrorCheck(arguments.organizationCode,arguments.FileId,organizationList,arguments.leasorID) />
```

So, probably the only time you'd want line breaks, in a cfset, is if there were a `STRUCT` which is being created inline by using the `{` syntax.

**Comment by prettydiff** [comment]
I can achieve that by passing object bodies to my JavaScript parser, even if in the middle of an attribute.  Its a good idea, because it has implications even outside of coldfusion.  I have some work to do to get this right.

**Comment by prettydiff** [comment]
Done.  Any kind of template tag whose attributes contain curly braces will have the contents of those curly braces formatted by my JavaScript parser.

**Comment by finalcut** [comment]
it looks really good; there is just one thing still (I feel like quite the nag) and it's related to `CFQUERY` again.. 

let's say you have this code:

```cfm
<cfquery name="q" datasource="#getDSN()#">
	SELECT *

	FROM	foobar_leasor c
	WHERE	1=1
	<cfif LEN(arguments.fromOrganizationCode)>
		<cfif arguments.fromOrganizationType EQ "R">
			AND op1.organization_code = <cfqueryparam cfsqltype="cf_sql_integer" value="#arguments.FromOrganizationCode#" />
		<cfelse>
			AND ts1.ts_oper = <cfqueryparam cfsqltype="cf_sql_integer" value="#arguments.FromOrganizationCode#" />
		</cfif>
	</cfif>
</cfquery>
```

the beautifier (because of the "pre" conditioning) does this:

```cfm
<cfquery name="q" datasource="#getDSN()#">
    SELECT *

    FROM	foobar_leasor c
    WHERE	1=1
    <cfif LEN(arguments.fromOrganizationCode)>
    <cfif arguments.fromOrganizationType EQ "R">
    AND op1.organization_code = <cfqueryparam cfsqltype="cf_sql_integer" value="#arguments.FromOrganizationCode#" />
    <cfelse>
    AND ts1.ts_oper = <cfqueryparam cfsqltype="cf_sql_integer" value="#arguments.FromOrganizationCode#" />
    </cfif>
    </cfif>
</cfquery>
```


It mucks up the `cfif` indentation. 



Oh.. and I thought of a couple other things that should be treated the same way `cfset` is in terms of not line wrapping them:

`cfargument`
`cfparam`

Those should always be single line entities.  They are used to define the arguments that can be passed into a method or module respectively.   It doesn't hurt them to be broken into multiple lines but it does seem strange to see them like that.

Here is an example:

```cfm
	<cffunction name="CreateOrganization" output="false" hint="creates a leasor organization record in the stats table">
		<cfargument name="organizationcode" type="any" required="true">
		<cfargument name="userID" type="numeric" required="false" default="#getDefaultUserID()#" />
	</cffunction>
```

becomes

```cfm
<cffunction
    hint="creates a leasor organization record in the stats table"
    name="CreateOrganization"
    output="false">
    <cfargument name="organizationcode" required="true" type="any">
    <cfargument
        default="#getDefaultUserID()#"
        name="userID"
        required="false"
        type="numeric"/>
</cffunction>
```

It just looks weird having one argument that is one one line and the other that spans multiple lines.

**Comment by prettydiff** [comment]
I have solved the latest cfquery request.  It took a great deal of effort and unmasked a lot of minor details I had not concerned with prior, but it works now.

As far as the indenting attributes. I could add an option so that attributes are:

* never indented
* indented according to the value of `wrap` option
* always indented

I will open an issue about that new option, but I want to ship CF support first.  Hopefully I am a bit closer to achieving support now.

**Comment by finalcut** [comment]
Sounds great. I'll test it again tomorrow.  If guess it's going to be ready
though.

On Sat, Dec 12, 2015, 14:56 Austin Cheney <notifications@github.com> wrote:

> I have solved the latest cfquery request. It took a great deal of effort
> and unmasked a lot of minor details I had not concerned with prior, but it
> works now.
>
> As far as the indenting attributes. I could add an option so that
> attributes are:
>
>    - never indented
>    - indented according to the value of wrap option
>    - always indented
>
> I will open an issue about that new option, but I want to ship CF support
> first. Hopefully I am a bit closer to achieving support now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prettydiff/prettydiff/issues/158#issuecomment-164185405>
> .
>
-- 
Bill

**Comment by finalcut** [comment]
I found a small problem that happens inside `cfquery`

Some important white space is removed around the SQL keyword "BETWEEN"

source:
```cfm

		   <CFIF arguments.offDate NEQ "/">
			<cfset local.endDate  = DaysInMonth("1/#arguments.offDate#") & "/#arguments.offDate#" />
			AND c.off_date  BETWEEN <cfqueryparam cfsqltype="cf_sql_date" value="1/#arguments.offDate#" />
								 AND <cfqueryparam cfsqltype="cf_sql_date" value="#local.endDate#" />
		   </CFIF>

```

result:

```cfm
            <CFIF arguments.offDate NEQ "/">
                <cfset local.endDate=DaysInMonth("1/#arguments.offDate#") & "/#arguments.offDate#"/>
                AND c.off_date BETWEEN<cfqueryparam cfsqltype="cf_sql_date" value="1/#arguments.offDate#"/>
                AND<cfqueryparam cfsqltype="cf_sql_date" value="#local.endDate#"/>
            </CFIF>
```

The argument after `BETWEEN` and after the final `AND` has no space before it and after the keyword so syntactically this will probably fail.

Spaces after the `=` also went away and after a `LIKE`

```cfm
                <CFSET arguments.searchString="%#arguments.searchString#%"/>
                AND c.comments LIKE<cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.searchString#"/>
            </CFIF>
```


I think this only happens if the code is inside a nested tag within the `CFQUERY`

For instance if I have:

```cfm
        <cfquery name="q" datasource="#getDSN()#">
            SELECT *
            FROM foobar_leasor_v2 c
            WHERE c.leasor_id = <cfqueryparam cfsqltype="cf_sql_integer" value="#arguments.leasorID#"/>
        </cfquery>
```

it is beautified fine and the space after the `=` and before the `cfqueryparam` remains intact but if I modify that query like so:

```cfm
        <cfquery name="q" datasource="#getDSN()#">
            SELECT *
            FROM foobar_leasor_v2 c
            WHERE c.leasor_id = <cfqueryparam cfsqltype="cf_sql_integer" value="#arguments.leasorID#"/>
			<cfif 1 EQ 1>
			 AND c.foobar = <cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.foobar#" />
			</cfif>
        </cfquery>
```

then I get 

```cfm
        <cfquery name="q" datasource="#getDSN()#">
            SELECT *
            FROM foobar_leasor_v2 c
            WHERE c.leasor_id = <cfqueryparam cfsqltype="cf_sql_integer" value="#arguments.leasorID#"/>
            <cfif 1 EQ 1>
                AND c.foobar =<cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.foobar#"/>
            </cfif>
        </cfquery>
```

**Comment by prettydiff** [comment]
Looks like I have completed that.  http://prettydiff.com/ignore/testlocation/lib/markuppretty.js

**Comment by finalcut** [comment]
I just noticed one more strange behavior sorry.. and it occurs with `cffunction`

If I have the following:

```cfm
<cfcomponent extends="BaseComponent">

	<cffunction name="create" output="false" returntype="numeric" hint="returns the leasor_id for the newly created leasor foobar record">
		<cfargument name="foobarcode"			type="numeric" 	required="true">


			<cfreturn getImportLeasor().CodeAndErrorCheck(argumentCollection = {
					, foobarCode 			=arguments.foobarCode
				}) />

	</cffunction>

</cfcomponent>
```

if I beautify it one time it's all good I get 

```cfm
<cfcomponent extends="BaseComponent">

    <cffunction
        hint="returns the leasor_id for the newly created leasor foobar record"
        name="create"
        output="false"
        returntype="numeric">
        <cfargument name="foobarcode" required="true" type="numeric">

        <cfreturn getImportLeasor().CodeAndErrorCheck(argumentCollection = {,
            foobarCode = arguments.foobarCode
        })/>

    </cffunction>

</cfcomponent>
```

but if I beautify it again a new blank line is injected after the `cffunction` (before the first attribute) and the `>` bracket at the end of the opening `cffunction` gets a bunch of whitespace (about 31 columns worth) before it.  Each subsequent beautification makes the spacing issue even worse


```cfm

<cfcomponent extends="BaseComponent">

    <cffunction

        hint="returns the leasor_id for the newly created leasor foobar record"
        name="create"
        output="false"
        returntype="numeric"                               >
        <cfargument name="foobarcode" required="true" type="numeric">

        <cfreturn getImportLeasor().CodeAndErrorCheck(argumentCollection = {,
            foobarCode = arguments.foobarCode
        })/>

    </cffunction>

</cfcomponent>
```

**Comment by finalcut** [comment]
just a little more info; this isn't entirely consistent (it doesn't happen to every `cffunction` ) I'm trying to get some more info for you.

**Comment by finalcut** [comment]
it only happens when you wrap the `cffunction` to deal with having a bunch of attributes that push the line beyond the line length threshold.

For instance, the weird spacing doesn't happen if the function above looks like this:

```cfm
    <cffunction name="create" output="false" returntype="numeric">
        <cfargument name="foobarcode" required="true" type="numeric">

        <cfreturn getImportLeasor().CodeAndErrorCheck(argumentCollection = {,
            foobarCode = arguments.foobarCode
        })/>

    </cffunction>
```

**Comment by prettydiff** [comment]
I can reproduce this easily on first beautification.  I am looking into it now.

**Comment by prettydiff** [comment]
I think I got one fixed too.

**Comment by finalcut** [comment]
well crap, I found another problem dealing with `<=` type operators inside `cfquery`

this is the input:

```cfm
									<cfquery name="c" datasource="#getDSN()#">
											SELECT certification_id
											  FROM aemis.pd_certification
											 WHERE certification = <cfqueryparam cfsqltype="cf_sql_varchar" value="#Trim(arguments.data.certification[arguments.data.currentRow])#">
											and open_py <= 2015 AND (close_py >= 2015 OR close_py IS NULL)
									</cfquery>
```

and here is the output:

```cfm
<cfquery name="c" datasource="#getDSN()#">
    SELECT certification_id
    FROM aemis.pd_certification
    WHERE certification = <cfqueryparam
        cfsqltype="cf_sql_varchar"
        value="#Trim(arguments.data.certification[arguments.data.currentRow])#">
    and open_py< (close_py >= 2015 OR close_py IS NULL) 2015 </cfquery> AND>
```

**Comment by prettydiff** [comment]
Fixed!  Another really good catch.

**Comment by finalcut** [comment]
not quite fixed... it is fixed for `<=` but for just `<` there is a problem:

input:

```cfm
<cfquery name="c" datasource="#getDSN()#">
		SELECT *
		  FROM foo
		 WHERE x < 2000
</cfquery>
```

output:

```cfm
<cfquery name="c" datasource="#getDSN()#">
    SELECT *
    FROM foo
    WHERE x
    < 200 </cfquery>>
```

the closing `</cfquery>` isn't left on the correct line and there is an additional `>` at the end.

it works fine if I just use an `>` like so:

```cfm
<cfquery name="c" datasource="#getDSN()#">
    SELECT *
    FROM foo
    WHERE x > 200
</cfquery>
```

**Comment by finalcut** [comment]
actually even with `<=` the closing `</cfquery>` is brought up to the wrong line but there isn't an extra `>` added.

**Comment by prettydiff** [comment]
I just updated the code.  I think this is fixed if `<` is not immediately followed by a letter, such as:

    <cfquery name="c" datasource="#getDSN()#">
        SELECT *
        FROM foo
        WHERE x <y
    </cfquery>

The parser will expect the `<y` to be the start of a tag. I am now ignoring numbers, white space, and `=` immediately following a `<` from a line of text as the start of the next tag.

**Comment by finalcut** [comment]
well here is a crappy one that you probably won't like. Hopefully you aren't regretting starting this CF parsing yet .


```cfm

<cftransaction>
	<cftry>
		<cfloop query="arguments.data">
			<!--- do some stuff.. doesn't matter.. --->

		</cfloop>
		<!--- everything worked, commit the transaction! --->
		<cftransaction action="commit"/>
		<cfcatch>
			<!--- something went wrong; roll back the transaction! --->
			<cftransaction action="rollback">
		</cfcatch>
	</cftry>
</cftransaction>

```

when beautified the inner `<cftransaction>` actions muck everything up.  This is a handy tag but as you can see it has some unusual behavior.

If a there is a `<cftransaction>` without any attributes it MUST have a closing tag - but it can have children `<cftransaction>` tags that don't have to have a closing tag..

cfml really is a crazy language sometimes..


here is the result of beautifiying that example:

```cfm
<cftransaction>
    <cftry>
        <cfloop query="arguments.data">
            <!--- do some stuff.. doesn't matter.. --->

        </cfloop>
        <!--- everything worked, commit the transaction! --->
        <cftransaction action="commit"/>
            <cfcatch>
                <!--- something went wrong; roll back the transaction! --->
                <cftransaction action="rollback">
                </cfcatch>
            </cftry>
        </cftransaction>
```

as you can see the indentation all goes to crap and it just cascades down from there messing everything that follows that first child `<cftransaction>`

**Comment by prettydiff** [comment]
Got that one too!

**Comment by finalcut** [comment]
Odd. I feel like this might be a regression; i'm not sure.

this input:

```cfm
						<cfif local.col EQ arguments.ignoreRowIfMissingDataInColumn AND NOT LEN(Trim(local.cellValue))>
							<cfset local.break = false />
							<!--- just get rid of this row since we think it is empty --->
							<cfset ArrayDeleteAt(local.ary,local.aryRowIndex) />
							<cfbreak>
						</cfif>

```

results in:

```cfm
<cfif
    local.col
    EQ
    arguments.ignoreRowIfMissingDataInColumn
    AND
    NOT
    LEN(Trim(local.cellValue))>
    <cfset local.break=false/>
    <!--- just get rid of this row since we think it is empty --->
    <cfset ArrayDeleteAt(local.ary,local.aryRowIndex)/>
    <cfbreak>
</cfif>
```

It isn't broken but it sure does look strange having the `cfif` statement so broken up.  

I see an actual bug I'll put in the next comment.

**Comment by prettydiff** [comment]
Am I safe in assuming that everything attributish that comes in a `cfif` tag is really just logic that build out a condition?  If so I will just add `cfif` and `cfelseif` to the omit list for attribute wrapping.

**Comment by finalcut** [comment]
yes.  That is a safe assumption.

**Comment by finalcut** [comment]
the thing I thought was a bug isn't actually a bug.. TIL.


this:

```cfm
                <cfscript>
                    foo.user.id = bar.user.getID();
                    foo.user.roles = bar.user.getRoles();
                    foo.user.jcdc = bar.user.getJdcdInd();
                    foo.user.admin = bar.user.getAdminInd();
                    foo.user.email = bar.user.getEmail();
                    foo.user.permission = "";
                </cfscript>
```

becomes 

```cfm
<cfscript>
    foo.user.id = bar
        .user
        .getID();
    foo.user.roles = bar
        .user
        .getRoles();
    foo.user.jcdc = bar
        .user
        .getJdcdInd();
    foo.user.admin = bar
        .user
        .getAdminInd();
    foo.user.email = bar
        .user
        .getEmail();
    foo.user.permission = "";
</cfscript>
```

which I didn't think would work when executed by the cfml compiler but it did.

**Comment by prettydiff** [comment]
I have a convention in place to break method chains onto new lines to ease reading in the case of really long chains.  I have been asked to make some changes to my approach in issue #227 though, specifically:

* provide a third option to leave method chains either broken or strung together depending upon how they are provided
* make my current approach more uniform.... at this time property chains are not broken if none of the properties are a method.

**Comment by prettydiff** [comment]
I went ahead the next release with these changes as there were fixes to other defects that needed to go out.  There may likely be more defects that still need to be patched, so I will keep this issue open for a bit longer and bump it to the next milestone.

**Comment by finalcut** [comment]
Sounds great.  I'll be able to test it a lot more one it's in atom
beautifier

On Mon, Dec 14, 2015, 19:24 Austin Cheney <notifications@github.com> wrote:

> I went ahead the next release with these changes as there were fixes to
> other defects that needed to go out. There may likely be more defects that
> still need to be patched, so I will keep this issue open for a bit longer
> and bump it to the next milestone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prettydiff/prettydiff/issues/158#issuecomment-164602700>
> .
>
-- 
Bill

**Comment by prettydiff** [comment]
In that case I will close this issue and get the ball rolling on ColdFusion language integration with Atom Beautify.
