### ISSUE TITLE
Liquid: beautify removing parts of tag

### ISSUE THREAD

**Issue by hughker** [prettydiff/prettydiff#287]
@prettydiff I was testing this out with the following Liquid code snippet and it appears to be removing the end of some tags

##### Input:
```
<div id="slider">
{% assign blog = blogs.[page.handle] %}
{% paginate blog.articles by 1000 %}
{% for article in blog.articles %}
<div class="slide-container">
<div class="image-overlay"></div>
<img src="{{ article.image.src | img_url: 'master' }}" alt="{{ article.title }}">
</div>
{% endfor %}
{% endpaginate %}
</div>
```

##### Output:
```
<div id="slider">
  {% assign blog = blogs.[page.handle]
  {% paginate blog.articles by 1000
  {% for article in blog.articles
    <div class="slide-container">
      <div class="image-overlay"></div>
      <img
        src="{{ article.image.src | img_url: 'master' }}"
        alt="{{ article.title }}">
    </div>
  {% endfor
  {% endpaginate
</div>
```

##### Pretty Diff Info:
```
Updated: 7 March 2016
Version: 1.16.28
```

##### Pretty Diff Comment:
```
/*prettydiff.com insize: "2", lang: "liquid", mode: "beautify" */
```

/cc @macdonaldr93 - wasn't sure if you were experiencing this as well by chance

**Comment by prettydiff** [comment]
Resolved on my local.  I will publish a patch tonight.

**Comment by prettydiff** [comment]
Solution is available for testing at http://prettydiff.com/ignore/testlocation/?m=beautify

**Comment by macdonaldr93** [comment]
@hughker yeah I was still having a few issues around end tags. I'll wait for this patch to be published then I'll start my testing again. Thanks @prettydiff

**Comment by prettydiff** [comment]
Published in v1.16.29.
