### ISSUE TITLE
Liquid whitespace comment tags

### ISSUE THREAD

**Issue by panoply** [prettydiff/prettydiff#586]
Using PrettyDiff to support Liquid formatting in VS Code with my [extension](https://github.com/panoply/vscode-liquid). Currently,  PrettyDiff has trouble with whitespace liquid comment tags, eg: `{%- comment -%}`:

**Defect Example**

![pretty-diff](https://user-images.githubusercontent.com/7041324/56603516-29460a80-6600-11e9-8488-15bc742946bf.gif)

> The current workaround I've implemented is to wrap `{%- comment -%}` tags within a `<div prettydiff-ignore>` right before applying formatting to prevent this defect from wreaking havoc thus ignoring these specific tags, see [here](https://github.com/panoply/vscode-liquid/blob/master/extension/index.js#L27)

**Comment by prettydiff** [comment]
```html
<a>
<%- comment -%>
 comment

<%- endcomment -%>
</a>
```

Is it safe to say that in this code example this is a single comment that should be treated as a single tag with all internal characters preserved?

**Comment by prettydiff** [comment]
Also, would you mind providing a code sample illustrating the defect so that I can reproduce the problem on my end.  Working from graphics is sometimes challenging to produce the code example the same way.

**Comment by panoply** [comment]
Apologies, Below is code sample:

Take the following input:

```html
{%- comment -%}
  Comment
{%- endcomment -%}
```

Will result in the following:

```html
{% comment %}{%- comment -%}{% endcomment %}
Comment{%- endcomment -%}
```

**Comment by prettydiff** [comment]
I just fixed this in the parser.  Simply run `npm update` on your project and the update should come in.  Please let me know if you encounter more problems.

**Comment by panoply** [comment]
Using PrettyDiff as a node module this issue persists, example: 

Before Beautify:

```
{%- comment -%}
  hello
{%- endcomment -%}
```

After Beautify: 
```
{% comment %}

  {%- comment -%}

{% endcomment %}
hello{%- endcomment -%}
```
The issue only occurs when attempting to beautify  whitespace comment liquid tags (which are comment tags that contain a dash `-`), eg: `{%- comment -%}` –  Non whitespace comment tags (`{% comment %}`) beautification will work as expected.
